auth:
  database: "crud_db"
  password: "supersecretpassword"
  username: "postgres"
  postgrespassword: "supersecretpassword"

persistence:
  size: 1Gi

volumePermissions:
  enabled: true

image:
  registry: docker.io
  repository: postgres
  tag: 15.11

  